function [field_map, training_data] = ...
    take_measurement_at_point(Rob, SimRob, field_map, ...
    training_data, gt_data, testing_data, gp_params, map_params)

global Map

dim_x = map_params.dim_x;
dim_y = map_params.dim_y;
dim_z = map_params.dim_z;

% Take a measurement - add to training data.
training_data.X_train = [training_data.X_train; Rob.state.x(1:3)'];
training_data.X_train_gt = [training_data.X_train_gt; SimRob.state.x(1:3)'];
r = Rob.state.r(1:3);
P = Map.P(r,r);
training_data.P_train(:,:,size(training_data.X_train,1)) = P;
training_data.Y_train = [training_data.Y_train; ...
    interp3(reshape(gt_data.X_gt(:,1),dim_y,dim_x,dim_z), ...
    reshape(gt_data.X_gt(:,2),dim_y,dim_x,dim_z), ...
    reshape(gt_data.X_gt(:,3),dim_y,dim_x,dim_z), ...
    reshape(gt_data.Y_gt,dim_y,dim_x,dim_z), ...
    SimRob.state.x(1), ...
    SimRob.state.x(2), ...
    SimRob.state.x(3))];

% Do GP regression.
cov_func_UI = {@covUI, gp_params.cov_func, gp_params.N_gauss, P};
[ymu, ys, fmu, fs, ~ , post] = ...
    gp(gp_params.hyp_trained, gp_params.inf_func, gp_params.mean_func, ...
    cov_func_UI, gp_params.lik_func, ...
    training_data.X_train, training_data.Y_train, testing_data.X_test);
field_map.mean = ymu;
field_map.cov = ys;

end
